// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCggmsaJdKJSgaIfesP1eGx5P5OkMhg7BY',
    appId: '1:433293866896:web:5d24788e9496625cf6a515',
    messagingSenderId: '433293866896',
    projectId: 'asqii-91828',
    authDomain: 'asqii-91828.firebaseapp.com',
    storageBucket: 'asqii-91828.appspot.com',
    measurementId: 'G-TS23XLR94Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZiIV8PxXGNX5ioUKaEHE7dUtXyIAk7Lc',
    appId: '1:433293866896:android:df4d82f37b7ea121f6a515',
    messagingSenderId: '433293866896',
    projectId: 'asqii-91828',
    storageBucket: 'asqii-91828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGqymlqgwBuKh8jddLJ-ENB95d966br0w',
    appId: '1:433293866896:ios:6300e58e0fb2ca57f6a515',
    messagingSenderId: '433293866896',
    projectId: 'asqii-91828',
    storageBucket: 'asqii-91828.appspot.com',
    iosBundleId: 'com.example.projetPfe',
  );
}
